name: Mirror Repository

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Mirror to epitech repo
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url: git@github.com:EpitechPromo2028/B-DOP-200-STG-2-1-bschocolatine-noe.carabin.git
          ssh_private_key: ${{ secrets.CHOCOLATINE2 }}
