##
## EPITECH PROJECT, 2023
## MAKEFILE MAIN
## File description:
## A program that do simple operation.
##

all:
	make -C ./lib/my

clean:
	make clean -C ./lib/my

fclean:	clean
	make fclean -C ./lib/my
	rm libhashtable.a

re:	fclean all
